In [1]:
# Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install torch

In [2]:
#!/usr/bin/env python
# coding: utf-8
# author: Wanjun  HUANG
# data: July 4th, 2021 
import torch
import numpy as np
import scipy.io
import torch.nn as nn
import torch.nn.functional as F
import time
import matplotlib.pyplot as plt
import math 
import os
import pandas as pd
import torch.utils.data as Data
from torch.autograd import Function
import gc
from scipy import sparse

global MAXMIN_V, MAXMIN_PQg,BRANFT,BUS_SLACK
global Ybus,baseMVA
global Real_Ptrain, Real_Qtrain, Real_Vmtrain, Real_Vatrain, Real_PQdtrain
global scale_vm, VmUb, VmLb, bus_slack, bus_PQg
global flagVm,flagVa,DELTA,flag_hisv,Nbus,Ntest

## whether there is GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)
print("Let's use", torch.cuda.device_count(), "GPUs!")

cpu
Let's use 0 GPUs!


In [3]:
## load system name
REPEAT = 1 #for speedup test: number of repeated computation 
s_epoch = 800 # minimum epoch for .pth model saving
p_epoch = 10 # print loss for each "p_epoch" epoch
model_version = 1 # version of model
Nbus = 118 # number of buses
sys_R = 1 # test case name
flag_test = 1 # 0-train model; 1-test well-trained model
flag_hisv = 1 # 1-use historical V to calculate dV;0-use predicted V to calculate dV
EpochVm = 100 # 2 # maximum epoch of Vm
EpochVa = 100 # 2 # maximum epoch of Va
batch_size_training = 100 # mini-batch size for training
batch_size_test = 1 # mini-batch size for test

In [4]:
# Load OPFLearn train data
data_dir = r"C:\Users\Trager Joswig-Jones\Documents\UW\Classes\EE554\project\datasets"
train_data_file = "pglib_opf_case118_ieee_80_000_samples_train.csv"
Nsample = 100_000
Nsample_train = 80_000

df = pd.read_csv(os.path.join(data_dir, train_data_file))
col_names = df.columns
data = df.to_numpy()
data = data[0:Nsample_train,:]

In [5]:
# Load OPFLearn test data
data_dir = r"C:\Users\Trager Joswig-Jones\Documents\UW\Classes\EE554\project\datasets"
test_data_file = "pglib_opf_case118_ieee_20_000_samples_test.csv"
Nsample_test = 20_000

df_test = pd.read_csv(os.path.join(data_dir, train_data_file))
col_names_test = df_test.columns
data_test = df_test.to_numpy()
data_test = data_test[0:Nsample_test,:]

In [6]:
## hyperparameters
Lrm = 1e-3 # learning rate for Vm
Lra = 1e-3 # learning rate for Va
k_dV = 1 # coefficient for dVa & dVm in post-processing
DELTA = 1e-4 # threshold of violation
scale_vm = torch.tensor([10]).float() # scaling of output Vm
scale_va = torch.tensor([10]).float() # scaling of output Va

# hidden layers for voltage magnitude (Vm) prediction
if Nbus == 300:
    khidden_Vm = np.array([8,6,4,2], dtype=int)
    khidden_Va = np.array([8,6,4,2], dtype=int)
    Neach = 12
else:
    khidden_Vm = np.array([8,4,2], dtype=int)
    khidden_Va = np.array([8,4,2], dtype=int) 
    Neach = Nsample / 10.
    
Ntrain = int(0.8 * Nsample)  # Using seperate training and test files
Ntest = int(0.2 * Nsample)  

#name of hidden layers for result saving
nmLm = 'Lm'
for i in range(khidden_Vm.shape[0]):
    nmLm = nmLm + str(khidden_Vm[i])
    
Lm = khidden_Vm.shape[0] # number of hidden layers

# hidden layers for voltage angles (Va) prediction
nmLa = 'La'
for i in range(khidden_Va.shape[0]):
    nmLa = nmLa + str(khidden_Va[i])    

La = khidden_Va.shape[0]  # number of hidden layers  

# results name
PATHVm = './modelvm'+str(Nbus)+'r'+str(sys_R)+'N'+str(model_version)+nmLm+'E'+str(EpochVm)+'.pth'
PATHVa = './modelva'+str(Nbus)+'r'+str(sys_R)+'N'+str(model_version)+nmLa+'E'+str(EpochVa)+'.pth'
PATHVms = './modelvm'+str(Nbus)+'r'+str(sys_R)+'N'+str(model_version)+nmLm
PATHVas = './modelva'+str(Nbus)+'r'+str(sys_R)+'N'+str(model_version)+nmLa
resultnm = './res_'+str(Nbus)+'r'+str(sys_R)+'M'+str(model_version)+'H'+str(flag_hisv)+ 'NT'+str(Ntrain) \
+'B'+str(batch_size_training) +'Em'+str(EpochVm)+'Ea'+str(EpochVa)+nmLm+nmLa+'rp'+str(REPEAT)+'.mat'

In [7]:
# load data case 118 network parameter data
matpara = scipy.io.loadmat('./data/pglib_opf_case'+str(Nbus)+'_ieeer'+str(sys_R)+'_para.mat')
load_idx = np.squeeze(matpara['load_idx']).astype(int) - 1  

# power system parameters
#RPd0 = mat['RPd'] # Pd, dataset
#RQd0 = mat['RQd'] # Qd, dataset
#RPg = mat['RPg'] # Pg, dataset
#RQg = mat['RQg'] # Qg, dataset
Ybus = matpara['Ybus']
Yf = matpara['Yf']
Yt = matpara['Yt']
bus_np = matpara['bus']
gen = matpara['gen']
gencost = matpara['gencost']
branch = matpara['branch']
baseMVA = matpara['baseMVA']
bus_slack = np.where(bus_np[:, 1] == 3)
bus_slack = np.squeeze(bus_slack)
BUS_SLACK = torch.from_numpy(bus_slack).long()
print('bus_slack', bus_slack)

# numpy array to spase matrix
Ybus = sparse.csr_matrix(Ybus)
Yf = sparse.csr_matrix(Yf) 
Yt = sparse.csr_matrix(Yt) 

# output data
#YVa = mat['RVa']*math.pi/180  # Voltage Angle, Dataset
# do not need to predict voltaeg angles of slack bus 
#YVa = np.delete(YVa, bus_slack, axis=1) 
#YVm = mat['RVm']  # Voltage Magnitude, Dataset
VmLb = matpara['VmLb'][0] # lower bound of Vm 
VmUb = matpara['VmUb'][0] # upper bound of Vm

# output data
#yva = YVa
#yvm = kvm
#print('yvm',yvm.shape,'yva',yva.shape)

bus_slack 68


In [8]:
# Parse data for train input and output data
inputs = data[:, 0:198]
RPd0 = inputs[:, 0:99].astype(float)
RQd0 = inputs[:, 99:198].astype(float)

v_outputs = data[:, 478:]  # Voltage Magnitude and Angle Data
YVm = v_outputs[:, 0:118].astype(float)
YVa_ = v_outputs[:, 118:].astype(float) * math.pi/180  # Convert from degrees to radians
YVa = np.delete(YVa_, bus_slack, axis=1)  # Remove voltage angle of slack bus 

gen_outputs = data[:, 198:360]
RPg = gen_outputs[:, 0:54].astype(float)
RQg = gen_outputs[:, 108:162].astype(float)

In [9]:
# Parse data for test input and output data
inputs_test = data_test[:, 0:198]
RPd0_test = inputs_test[:, 0:99].astype(float)
RQd0_test = inputs_test[:, 99:198].astype(float)

v_outputs_test = data_test[:, 478:]  # Voltage Magnitude and Angle Data
YVm_test = v_outputs_test[:, 0:118].astype(float)
YVa_test = v_outputs_test[:, 118:].astype(float) * math.pi/180  # Convert from degrees to radians
YVa_test = np.delete(YVa_test, bus_slack, axis=1)  # Remove voltage angle of slack bus 

gen_outputs_test = data_test[:, 198:360]
RPg_test = gen_outputs_test[:, 0:54].astype(float)
RQg_test = gen_outputs_test[:, 108:162].astype(float)

In [10]:
# Input Data
x = np.concatenate((RPd0, RQd0), axis = 1)  # Input data in per unit
x_test = np.concatenate((RPd0_test, RQd0_test), axis = 1)  # Input data in per unit
print('x', x.shape)

x (80000, 198)


In [11]:
# Output Data
kvm = (YVm - VmLb)/(VmUb - VmLb) # Vm scaled with bounds
kvm_test = (YVm_test - VmLb)/(VmUb - VmLb) # Vm scaled with bounds


# output data
yva = YVa
yvm = kvm

yva_test = YVa_test
yvm_test = kvm_test
print('yvm',yvm.shape,'yva',yva.shape)

yvm (80000, 118) yva (80000, 117)


In [12]:
# Pg Qg data: only contain generators that are turned on
idxPg = np.squeeze(np.where(gen[:, 3] > 0), axis=0)
idxQg = np.squeeze(np.where(gen[:, 1] > 0), axis=0)

# Pd Qd of samples
RPd = np.zeros((Nsample_train,Nbus))
RQd = np.zeros((Nsample_train,Nbus))
RPd[:, load_idx] = RPd0[0:Nsample_train]
RQd[:, load_idx] = RQd0[0:Nsample_train]

RPd_test = np.zeros((Nsample_test,Nbus))
RQd_test = np.zeros((Nsample_test,Nbus))
RPd_test[:, load_idx] = RPd0_test[0:Nsample_test]
RQd_test[:, load_idx] = RQd0_test[0:Nsample_test]

del RPd0, RQd0
gc.collect()

7

In [13]:
bus_Pg = gen[idxPg, 0].astype(int) - 1
bus_Qg = gen[idxQg, 0].astype(int) - 1
bus_PQg = np.concatenate((bus_Pg, bus_Qg + Nbus), axis = 0)
MAXMIN_Pg = gen[idxPg, 3:5]/baseMVA
MAXMIN_Qg = gen[idxQg, 1:3]/baseMVA
MAXMIN_PQg = np.concatenate((MAXMIN_Pg, MAXMIN_Qg), axis = 0) #[Npg+NQg, 2]

# numpy to tensor and output data scaling
MAXMIN_PQg = torch.from_numpy(MAXMIN_Pg).float()
bus = torch.from_numpy(bus_np).float()
bus_PQg = torch.from_numpy(bus_PQg)
VmLb = torch.from_numpy(VmLb).float()
VmUb = torch.from_numpy(VmUb).float()
yvm = torch.from_numpy(yvm).float()
yva = torch.from_numpy(yva).float()
yvms = yvm*scale_vm
yvas = yva*scale_va

yvm_test = torch.from_numpy(yvm_test).float()
yva_test = torch.from_numpy(yva_test).float()
yvms_test = yvm_test*scale_vm
yvas_test = yva_test*scale_va

# constraints violation: Vm 
MAXMIN_V = (bus[:, 2:4] - VmLb)*scale_vm/(VmUb - VmLb)
MAXMIN_Vpu = bus[0,2:4]

# branch angle incidence matrix
BRANFT = torch.from_numpy(branch[:, 0:2] - 1).long()

# loss function
criterion = nn.MSELoss()

# convert training data to tensor
x_tensor = torch.from_numpy(x).float()
yvm_tensor = yvms.float()
yva_tensor = yvas.float()
xtrain = x_tensor[0: Ntrain]
yvmtrain = yvm_tensor[0: Ntrain]
yvatrain = yva_tensor[0: Ntrain]

# batch data
training_dataset_vm = Data.TensorDataset(xtrain, yvmtrain)
training_loader_vm = Data.DataLoader(
        dataset=training_dataset_vm,
        batch_size=batch_size_training,
        shuffle=False,
    )             

training_dataset_va = Data.TensorDataset(xtrain, yvatrain)
training_loader_va = Data.DataLoader(
        dataset=training_dataset_va,
        batch_size=batch_size_training,
        shuffle=False,
    )

# test data
x_test_tensor = torch.from_numpy(x_test).float()
yvm_test_tensor = yvms_test.float()
yva_test_tensor = yva_test.float()
xtest = x_test_tensor
yvmtest = yvm_test_tensor
yvatest = yva_test_tensor

# batch data
batch_size_test = 1
test_dataset_vm = Data.TensorDataset(xtest, yvmtest)
test_loader_vm = Data.DataLoader(
        dataset=test_dataset_vm,
        batch_size=batch_size_test,
        shuffle=False,
    )             

test_dataset_va = Data.TensorDataset(xtest, yvatest)
test_loader_va = Data.DataLoader(
        dataset=test_dataset_va,
        batch_size=batch_size_test,
        shuffle=False,
    )

print('yvmtrain',torch.min(yvmtrain), torch.max(yvmtrain))
print('yvatrain',torch.min(yvatrain), torch.max(yvatrain))

# test load generation
Pdtest = RPd_test[:]  # Already in baseMVA pu
Qdtest = RQd_test[:]
Pgtest = RPg_test[:, idxPg]
Qgtest = RQg_test[:, idxQg]
Qgtest = Qgtest.squeeze()

# historical voltage
Real_Vmtrain = yvmtrain/scale_vm*(VmUb - VmLb) + VmLb
Real_Vatrain = yvatrain/scale_va
hisVm_max,_ = torch.max(Real_Vmtrain, dim=0)
hisVm_min,_ = torch.min(Real_Vmtrain, dim=0)
his_Va = np.mean(np.insert(Real_Vatrain.numpy(), bus_slack, values = 0, axis=1),axis=0)
his_Vm = np.mean(Real_Vmtrain.numpy(), axis=0)
his_V = his_Vm * np.exp(1j * his_Va) # historical V

yvmtrain tensor(0.) tensor(10.)
yvatrain tensor(-0.1315) tensor(0.0722)


In [14]:
## other function
def get_clamp(Pred, Predmin, Predmax):
    # each row is a sample;Predmin and Predmax is the limit for each element of each row
    Pred_clip = Pred.clone()
    for i in range(Pred.shape[1]):
        Pred_clip[:,i] = Pred_clip[:,i].clamp(min = Predmin[i])
        Pred_clip[:,i] = Pred_clip[:,i].clamp(max = Predmax[i])
    
    return Pred_clip

# testing Vm
def get_mae(real, predict):
    '''
    mean absolute error
    '''
    if len(real) == len(predict):
        err = torch.mean(torch.abs(real - predict))  
        return err
    else:
        return None
    
def get_rerr(real, predict):
    '''
    relative error
    '''
    if len(real) == len(predict):
        err = torch.abs((predict - real) / real)*100
        return err
    else:
        return None
    
def get_rerr2(real, predict):
    '''
    relative error
    '''
    if len(real) == len(predict):
        err = (predict - real) / real*100
        return err
    else:
        return None
    
# power balance
def get_PQ(V):
    S = np.zeros(V.shape,dtype = 'complex_')
    for i in range(V.shape[0]):
        I = Ybus.dot(V[i]).conj()
        S[i]  = np.multiply(V[i], I)
    
    P = np.real(S)
    Q = np.imag(S) 
    return P, Q

def get_genload(V, Pdtest, Qdtest, bus_Pg, bus_Qg):
    S = np.zeros(V.shape,dtype = 'complex_')
    for i in range(V.shape[0]):
        I = Ybus.dot(V[i]).conj()
        S[i]  = np.multiply(V[i], I)
    
    P = np.real(S)
    Q = np.imag(S) 
    
    # Add sample load to calc power at generator buses to get the generator power
    # Positive P is power injected into the bus, Negative P is power demand at the bus
    Pg = P[:, bus_Pg] + Pdtest[:, bus_Pg]  # Injected power + Load Demand power
    Qg = Q[:, bus_Qg] + Qdtest[:, bus_Qg]   
    Pd = -P*1.0  # Load is the demanded power at the bus
    Qd = -Q*1.0  # These values may differ from the sample demand...
    Pd[:, bus_Pg] = Pg - P[:, bus_Pg]  # Need to account for generation
    Qd[:, bus_Qg] = Qg - Q[:, bus_Qg]  # Returns these buses to Pd/Qdtest
    return Pg, Qg, Pd, Qd


# cost
def get_Pgcost(Pg,idxPg,gencost):
    cost = np.zeros(Pg.shape[0])
    PgMVA = Pg*baseMVA
    PgMVA = Pg*baseMVA
    for i in range(Pg.shape[0]): 
        c1 = np.multiply(gencost[idxPg, 0], np.multiply(PgMVA[i,:], PgMVA[i,:]))
        c2 = np.multiply(gencost[idxPg, 1], PgMVA[i,:])
        cost[i] = np.sum(c1 + c2)
            
    return cost

In [15]:
## NN function
class NetVa(nn.Module):
    def __init__(self, input_channels, output_channels, hidden_units,khidden):
        super(NetVa, self).__init__()
        #''' 
        self.num_layer = khidden.shape[0]
        
        self.fc1 = nn.Linear(input_channels, khidden[0]*hidden_units)  
        if self.num_layer >= 2: 
            self.fc2 = nn.Linear(khidden[0]*hidden_units, khidden[1]*hidden_units)
        
        if self.num_layer >= 3:
            self.fc3 = nn.Linear(khidden[1]*hidden_units, khidden[2]*hidden_units)
        
        if self.num_layer >= 4:
            self.fc4 = nn.Linear(khidden[2]*hidden_units, khidden[3]*hidden_units)
            
        if self.num_layer >= 5:
            self.fc5 = nn.Linear(khidden[3]*hidden_units, khidden[4]*hidden_units)
            
        if self.num_layer >= 6:
            self.fc6 = nn.Linear(khidden[4]*hidden_units, khidden[5]*hidden_units)
            
            
        self.fcbfend = nn.Linear(khidden[khidden.shape[0]-1]*hidden_units, output_channels)   
        self.fcend = nn.Linear(output_channels, output_channels)  

    def forward(self, x):
        x = F.relu(self.fc1(x))
        
        if self.num_layer >= 2:
            x = F.relu(self.fc2(x))
            
        if self.num_layer >= 3:
            x = F.relu(self.fc3(x))
            
        if self.num_layer >= 4:
            x = F.relu(self.fc4(x))
        
        if self.num_layer >= 5:
            x = F.relu(self.fc5(x))
            
        if self.num_layer >= 6:
            x = F.relu(self.fc6(x))
        
        # fixed final two layers
        x = F.relu(self.fcbfend(x))
        x_PredVa = self.fcend(x)
                
        return x_PredVa
        

class NetVm(nn.Module):
    def __init__(self, input_channels, output_channels, hidden_units,khidden):
        super(NetVm, self).__init__()
        self.num_layer = khidden.shape[0]
        self.fc1 = nn.Linear(input_channels, khidden[0]*hidden_units)
        if self.num_layer >= 2: 
            self.fc2 = nn.Linear(khidden[0]*hidden_units, khidden[1]*hidden_units)
        
        if self.num_layer >= 3:
            self.fc3 = nn.Linear(khidden[1]*hidden_units, khidden[2]*hidden_units)
        
        if self.num_layer >= 4:
            self.fc4 = nn.Linear(khidden[2]*hidden_units, khidden[3]*hidden_units)
            
        if self.num_layer >= 5:
            self.fc5 = nn.Linear(khidden[3]*hidden_units, khidden[4]*hidden_units)
            
        if self.num_layer >= 6:
            self.fc6 = nn.Linear(khidden[4]*hidden_units, khidden[5]*hidden_units)
            
            
        self.fcbfend = nn.Linear(khidden[khidden.shape[0]-1]*hidden_units, output_channels)   
        self.fcend = nn.Linear(output_channels, output_channels) 
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        
        if self.num_layer >= 2:
            x = F.relu(self.fc2(x))
            
        if self.num_layer >= 3:
            x = F.relu(self.fc3(x))
            
        if self.num_layer >= 4:
            x = F.relu(self.fc4(x))
        
        if self.num_layer >= 5:
            x = F.relu(self.fc5(x))
            
        if self.num_layer >= 6:
            x = F.relu(self.fc6(x))
        
        # fixed final two layers
        x = F.relu(self.fcbfend(x))
        x_PredVm = self.fcend(x)

        return x_PredVm

In [16]:
## violation calculation function
# Pg Qg violation
def get_vioPQg(Pred_Pg, bus_Pg, MAXMIN_Pg, Pred_Qg, bus_Qg, MAXMIN_Qg):
    vio_PQgmaxminnum = torch.zeros((Pred_Pg.shape[0],4))
    vio_PQgmaxmin = torch.zeros((Pred_Pg.shape[0],4))
    vio_PQg = torch.zeros((Pred_Pg.shape[0],2))
    lsPg = list()
    lsQg = list()
    lsidxPg = np.zeros((Pred_Pg.shape[0]),dtype = np.int) # index of sample that has violation
    lsidxQg = np.zeros((Pred_Pg.shape[0]),dtype = np.int) # index of sample that has violation
    kP = 1 # violated samples index
    kQ = 1 # violated samples index
    deltaPgL = np.array([[0, 0]])
    deltaPgU = np.array([[0, 0]])
    deltaQgL = np.array([[0, 0]])
    deltaQgU = np.array([[0, 0]])
    for i in range(Pred_Pg.shape[0]):
        # P
        delta = Pred_Pg[i] - MAXMIN_Pg[:, 0]
        idxPgUB = np.array(np.where(delta > DELTA))
        if np.size(idxPgUB) > 0:
            PgUB = np.concatenate((idxPgUB,delta[idxPgUB]),axis=0).T 
            deltaPgU = np.append(deltaPgU, PgUB, axis = 0)

        delta = Pred_Pg[i] - MAXMIN_Pg[:, 1]
        idxPgLB = np.array(np.where(delta < -DELTA))
        if np.size(idxPgLB) > 0:
            PgLB = np.concatenate((idxPgLB,delta[idxPgLB]),axis=0).T
            deltaPgL = np.append(deltaPgL, PgLB, axis = 0)
        
        if np.size(idxPgUB)>0 and np.size(idxPgLB) > 0:
            PgLUB = np.concatenate((PgUB,PgLB),axis=0)
        elif np.size(idxPgUB) > 0:
            PgLUB = PgUB
        elif np.size(idxPgLB) > 0:
            PgLUB = PgLB
        
        if (np.size(idxPgUB) + np.size(idxPgLB)) > 0:
            PgLUB = PgLUB[PgLUB[:,0].argsort()]
            lsPg.append(PgLUB)
            lsidxPg[i] = kP # has violation:index of lsPg 
            kP+= 1#index=lsPg

        # Q
        delta = Pred_Qg[i] - MAXMIN_Qg[:, 0]
        idxQgUB = np.array(np.where(delta > DELTA))
        if np.size(idxQgUB) > 0:
            QgUB = np.concatenate((idxQgUB,delta[idxQgUB]),axis=0).T
            deltaQgU = np.append(deltaQgU, QgUB, axis = 0)

        delta = Pred_Qg[i] - MAXMIN_Qg[:, 1]
        idxQgLB = np.array(np.where(delta < -DELTA))
        if np.size(idxQgLB) > 0:
            QgLB = np.concatenate((idxQgLB,delta[idxQgLB]),axis=0).T
            deltaQgL = np.append(deltaQgL, QgLB, axis = 0)
            
        if np.size(idxQgUB) >0 and np.size(idxQgLB) > 0:   
            QgLUB = np.concatenate((QgUB,QgLB),axis=0)
        elif np.size(idxQgUB) > 0:
            QgLUB = QgUB
        elif np.size(idxQgLB) > 0:
            QgLUB = QgLB
         
        if (np.size(idxQgUB) + np.size(idxQgLB)) > 0:
            QgLUB = QgLUB[QgLUB[:,0].argsort()]
            lsQg.append(QgLUB)
            lsidxQg[i] = kQ # has violation
            kQ+= 1
                    
        
        vio_PQgmaxminnum[i,0] = np.size(idxPgUB)
        vio_PQgmaxminnum[i,1] = np.size(idxPgLB)
        vio_PQgmaxminnum[i,2] = np.size(idxQgUB)
        vio_PQgmaxminnum[i,3] = np.size(idxQgLB)
        
    # Pg Qg violation ratio
    vio_PQgmaxmin[:,0] = (1 - vio_PQgmaxminnum[:, 0]/bus_Pg.shape[0])*100
    vio_PQgmaxmin[:,1] = (1 - vio_PQgmaxminnum[:, 1]/bus_Pg.shape[0])*100
    vio_PQgmaxmin[:,2] = (1 - vio_PQgmaxminnum[:, 2]/bus_Qg.shape[0])*100
    vio_PQgmaxmin[:,3] = (1 - vio_PQgmaxminnum[:, 3]/bus_Qg.shape[0])*100
    vio_PQg[:, 0] = (1 - (vio_PQgmaxminnum[:, 0] + vio_PQgmaxminnum[:, 1])/bus_Pg.shape[0])*100
    vio_PQg[:, 1] = (1 - (vio_PQgmaxminnum[:, 2] + vio_PQgmaxminnum[:, 3])/bus_Qg.shape[0])*100
     
    # delete initial 
    if deltaPgL.shape[0] > 1:
        deltaPgL = np.delete(deltaPgL, 0, axis = 0)
        
    if deltaPgU.shape[0] > 1:    
        deltaPgU = np.delete(deltaPgU, 0, axis = 0)
    
    if deltaQgL.shape[0] > 1:
        deltaQgL = np.delete(deltaQgL, 0, axis = 0)
    
    if deltaQgU.shape[0] > 1:
        deltaQgU = np.delete(deltaQgU, 0, axis = 0)
    
    return lsPg,lsQg,lsidxPg,lsidxQg,vio_PQgmaxmin,vio_PQg, deltaPgL,deltaPgU,deltaQgL,deltaQgU,vio_PQgmaxminnum

In [17]:
# modify V theta
# dPbus_dV dQbus_dV
def dPQbus_dV(his_V,bus_Pg,bus_Qg):
    V = his_V.copy()
#     Ibus = np.dot(Ybus, his_V)
    Ibus = Ybus.dot(his_V).conj()
    diagV = np.diag(V)
    diagIbus = np.diag(Ibus)
    diagVnorm = np.diag(V/np.abs(V))
    dSbus_dVm = np.dot(diagV, Ybus.dot(diagVnorm).conj()) + np.dot(diagIbus.conj(), diagVnorm)
    dSbus_dVa = 1j*np.dot(diagV, (diagIbus - Ybus.dot(diagV)).conj())
    dSbus_dV = np.concatenate((dSbus_dVa, dSbus_dVm), axis=1)
    dPbus_dV = np.real(dSbus_dV)
    dQbus_dV = np.imag(dSbus_dV)
    
    return dPbus_dV,dQbus_dV

# calculate dV using historical V
def get_hisdV(lsPg,lsQg,lsidxPg,lsidxQg,num_viotest,k_dV,bus_Pg,bus_Qg,dPbus_dV,dQbus_dV):
    dV = np.zeros((num_viotest,Nbus*2))
    j = 0
    for i in range(Ntest):
        # determin whether there is violation
        if (lsidxPg[i] + lsidxQg[i]) > 0:
            # calculate dS_dV, dPbus_dV,dQbus_dV
            if lsidxPg[i] >0 and lsidxQg[i] >0:
                idxPg = lsPg[lsidxPg[i]-1][:,0].astype(np.int32) #note: lsidxPg[i]-1
                idxQg = lsQg[lsidxQg[i]-1][:,0].astype(np.int32) #note: lsidxQg[i]-1
                busPg = bus_Pg[idxPg]
                busQg = bus_Qg[idxQg]
                dPQGbus_dV = np.concatenate((dPbus_dV[busPg, :], dQbus_dV[busQg, :]), axis=0) #need bus number pf Pg Qg
                dPQg = np.concatenate((lsPg[lsidxPg[i]-1][:,1], lsQg[lsidxQg[i]-1][:,1]), axis=0)
            elif lsidxPg[i] >0:  
                idxPg = lsPg[lsidxPg[i]-1][:,0].astype(np.int32)
                busPg = bus_Pg[idxPg]
                dPQGbus_dV = dPbus_dV[busPg, :]
                dPQg = lsPg[lsidxPg[i]-1][:,1]
            elif lsidxQg[i] >0:     
                idxQg = lsQg[lsidxQg[i]-1][:,0].astype(np.int32)
                busQg = bus_Qg[idxQg]
                dPQGbus_dV = dQbus_dV[busQg, :]
                dPQg = lsQg[lsidxQg[i]-1][:,1]

            dV[j] = np.dot(np.linalg.pinv(dPQGbus_dV), dPQg*k_dV)           
            j+=1   
            
    return dV

# # calculate dV using predicted V
# lsidxtest is the test sample that has violation
def get_dV(Pred_V,lsPg,lsQg,lsidxPg,lsidxQg,num_viotest,k_dV,bus_Pg,bus_Qg):
    dV = np.zeros((num_viotest,Pred_V.shape[1]*2))
    j = 0
    for i in range(Pred_V.shape[0]):
        # determin whether there is violation
        if (lsidxPg[i] + lsidxQg[i]) >0:
            # dS_dV
            V = Pred_V[i].copy()
            Ibus = Ybus.dot(his_V).conj()
            diagV = np.diag(V)
            diagIbus = np.diag(Ibus)
            diagVnorm = np.diag(V/np.abs(V))

            dSbus_dVm = np.dot(diagV, Ybus.dot(diagVnorm).conj()) + np.dot(diagIbus.conj(), diagVnorm)
            dSbus_dVa = 1j*np.dot(diagV, (diagIbus - Ybus.dot(diagV)).conj())
            
            dSbus_dV = np.concatenate((dSbus_dVa, dSbus_dVm), axis=1)
            dPbus_dV = np.real(dSbus_dV)
            dQbus_dV = np.imag(dSbus_dV)
            # get BusPg
            if lsidxPg[i] >0 and lsidxQg[i] >0:
                idxPg = lsPg[lsidxPg[i]-1][:,0].astype(np.int32) #note: lsidxPg[i]-1
                idxQg = lsQg[lsidxQg[i]-1][:,0].astype(np.int32) #note: lsidxQg[i]-1
                busPg = bus_Pg[idxPg]
                busQg = bus_Qg[idxQg]
                dPQGbus_dV = np.concatenate((dPbus_dV[busPg, :], dQbus_dV[busQg, :]), axis=0) #need bus number pf Pg Qg
                dPQg = np.concatenate((lsPg[lsidxPg[i]-1][:,1], lsQg[lsidxQg[i]-1][:,1]), axis=0)
            elif lsidxPg[i] >0:  
                idxPg = lsPg[lsidxPg[i]-1][:,0].astype(np.int32)
                busPg = bus_Pg[idxPg]
                dPQGbus_dV = dPbus_dV[busPg, :]
                dPQg = lsPg[lsidxPg[i]-1][:,1]
            elif lsidxQg[i] >0:     
                # get BusQg
                idxQg = lsQg[lsidxQg[i]-1][:,0].astype(np.int32)
                busQg = bus_Qg[idxQg]
                dPQGbus_dV = dQbus_dV[busQg, :]
                dPQg = lsQg[lsidxQg[i]-1][:,1]

            dV[j] = np.dot(np.linalg.pinv(dPQGbus_dV), dPQg*k_dV)           
            j+=1        
    return dV

In [18]:
# branch constraints
def get_viobran(Pred_V,Pred_Va,branch,Yf,Yt):
   #branch format: [branch from bus, branch to bus, branch limit, minang, maxang]
    branlp = branch[:, 2]
    angminmax = branch[:, 3:5]*math.pi/180
    Pred_branang = Pred_Va[:, BRANFT[:, 0]] - Pred_Va[:, BRANFT[:, 1]]
    vio_branangnum = torch.zeros(Pred_V.shape[0])
    vio_branpfnum = torch.zeros(Pred_V.shape[0])
    deltapf = np.array([[0, 0]])
    for i in range(Pred_V.shape[0]):
    #for i in range(1):
        vio_branangnum[i] = np.size(np.where(Pred_branang[i, :] - angminmax[:,0] < -DELTA)) \
        + np.size(np.where(Pred_branang[i, :] - angminmax[:,1] > DELTA))

        # branch power flow
        fV = Pred_V[i, BRANFT[:, 0]]
        tV = Pred_V[i, BRANFT[:, 1]]
        fI = Yf.dot(Pred_V[i]).conj()
        tI = Yt.dot(Pred_V[i]).conj()       
        fS = np.multiply(fV, fI)
        tS = np.multiply(tV, tI)
        deltafS = np.abs(fS) - branlp
        deltatS = np.abs(tS) - branlp
        deltafS = np.array(deltafS).ravel()
        deltatS = np.array(deltatS).ravel()
        idxfs = np.array(np.where(deltafS > DELTA))
        idxts = np.array(np.where(deltatS > DELTA))
        vio_branpfnum[i] = np.size(idxfs) + np.size(idxfs)
        
        # save violated samples [index-of-branch violation-degree]
        if np.size(idxfs) >= 1:
            ii = np.concatenate((idxfs,deltafS[idxfs]),axis=0)
            deltapf = np.append(deltapf, ii.T, axis = 0)
            
        if np.size(idxts) >= 1:
            ii = np.concatenate((idxts,deltatS[idxts]),axis=0)
            deltapf = np.append(deltapf, ii.T, axis = 0) 
            
    # delete initial
    if deltapf.shape[0] > 1:
        deltapf = np.delete(deltapf, 0, axis = 0)
        deltapfR = deltapf[:, 1]/branlp[0,deltapf[:, 0].astype(int)]*100
        deltapf = np.insert(deltapf, 2, values=deltapfR, axis=1)
 
    vio_branang = (1-vio_branangnum/branch.shape[0])*100 
    vio_branpf = (1-vio_branpfnum/(branch.shape[0]*2))*100
    return vio_branang,vio_branpf,deltapf,vio_branangnum,vio_branpfnum

In [19]:
# branch constraints with violation details for dV
def get_viobran2(Pred_V,Pred_Va,branch,Yf,Yt):
   #branch=[branch from bus, branch to bus, branch limit, minang, maxang]
    branlp = branch[:, 2]/baseMVA
    angminmax = branch[:, 3:5]*math.pi/180
    Pred_branang = Pred_Va[:, BRANFT[:, 0]] - Pred_Va[:, BRANFT[:, 1]]
    vio_branangnum = torch.zeros(Pred_V.shape[0])
    vio_branpfnum = torch.zeros(Pred_V.shape[0])
    vio_branpfidx = torch.zeros(Pred_V.shape[0])
    lsSf = []
    lsSt = []
    lsSf_sampidx = []
    lsSt_sampidx = []
    deltapf = np.array([[0, 0]])
    for i in range(Pred_V.shape[0]):
    #for i in range(1):
        vio_branangnum[i] = np.size(np.where(Pred_branang[i, :] - angminmax[:,0] < -DELTA)) \
        + np.size(np.where(Pred_branang[i, :] - angminmax[:,1] > DELTA))

        # branch power flow
        fV = Pred_V[i, BRANFT[:, 0]]
        tV = Pred_V[i, BRANFT[:, 1]]        
        fI = Yf.dot(Pred_V[i]).conj()
        tI = Yt.dot(Pred_V[i]).conj()
        fS = np.multiply(fV, fI)
        tS = np.multiply(tV, tI)
        deltafS = np.abs(fS) - branlp
        deltatS = np.abs(tS) - branlp
        deltafS = np.array(deltafS).ravel()
        deltatS = np.array(deltatS).ravel()
        idxfs = np.array(np.where(deltafS > DELTA)).reshape(-1, 1)
        idxts = np.array(np.where(deltatS > DELTA)).reshape(-1, 1)
        vio_branpfnum[i] = np.size(idxfs) + np.size(idxfs)
        if np.size(idxfs) >= 1:           
            ii = np.concatenate((idxfs,deltafS[idxfs]),axis=1)  
            deltapf = np.append(deltapf, ii, axis = 0) 
            ii = np.concatenate((ii,np.real(fS[idxfs]),np.imag(fS[idxfs])),axis=1)
            lsSf.append(ii)
            lsSf_sampidx.append(i)           
            
        if np.size(idxts) >= 1:
            ii = np.concatenate((idxts,deltatS[idxts]),axis=1)
            deltapf = np.append(deltapf, ii, axis = 0) 
            ii = np.concatenate((ii,np.real(tS[idxts]),np.imag(tS[idxts])),axis=1)
            lsSt.append(ii)
            lsSt_sampidx.append(i)

        if np.size(idxfs) + np.size(idxts) >= 1:
            vio_branpfidx[i] = i+1
            
    # delete initial
    if deltapf.shape[0] > 1:
        deltapf = np.delete(deltapf, 0, axis = 0)
        deltapfR = deltapf[:, 1]/branlp[deltapf[:, 0].astype(int)]*100
        deltapf = np.insert(deltapf, 2, values=deltapfR, axis=1)
 
    vio_branang = (1-vio_branangnum/branch.shape[0])*100 
    vio_branpf = (1-vio_branpfnum/(branch.shape[0]*2))*100
    return vio_branang,vio_branpf,deltapf,vio_branpfidx,lsSf,lsSt,lsSf_sampidx,lsSt_sampidx

def dSlbus_dV(his_V,bus_Va):
    V = his_V.copy()
    branlp = branch[:, 2]/baseMVA
    # branch power flow for FROM branch
    fV = V[BRANFT[:, 0]]
    fI = Yf.dot(V).conj()
    Nsam = 1
    dfP_dVm = np.zeros((Nsam, branch.shape[0], Nbus))   
    dfQ_dVm = np.zeros((Nsam, branch.shape[0], Nbus))
    dfP_dVa = np.zeros((Nsam, branch.shape[0], Nbus-1))    
    dfQ_dVa = np.zeros((Nsam, branch.shape[0], Nbus-1))                
    diagfI = np.diag(fI)
    diagfV = np.diag(fV)
    diagVnorm = np.diag(np.true_divide(V, np.abs(V)))
#     print('diagfV',diagfV.shape,'diagVnorm',diagVnorm.shape,'Yf',Yf.shape,'diagfI',diagfI.shape,'finc',finc.shape)
    dfS_dVm = np.dot(diagfV, Yf.dot(diagVnorm).conj()) + np.dot(diagfI.conj(), np.dot(finc,diagVnorm))
    dfP_dVm = np.real(dfS_dVm)
    dfQ_dVm = np.imag(dfS_dVm)
    diagV = np.diag(V)
    dfS_dVa = -1j*np.dot(diagfV, Yf.dot(diagV).conj()) + 1j*np.dot(diagfI.conj(), np.dot(finc, diagV))
    dfP_dVa = np.real(dfS_dVa[:, bus_Va])
    dfQ_dVa = np.imag(dfS_dVa[:, bus_Va])
    dPfbus_dV = np.concatenate((dfP_dVa, dfP_dVm), axis = 1)
    dQfbus_dV = np.concatenate((dfQ_dVa, dfQ_dVm), axis = 1)

#     for TO branch
#     fI = np.zeros((V.shape[0], branch.shape[0]), dtype=complex)
#     tI = np.zeros((V.shape[0], branch.shape[0]), dtype=complex)
#     tV = V[0, BRANFT[:, 1]]
#     tI = Yt.dot(Yt, V).conj()
#     tS  = np.multiply(tV, tI)    
#     diagtI = np.diag(tI)
#     diagtV = np.diag(tV)
#     dtP_dVm = np.zeros((Nsam, branch.shape[0], Nbus))
#     dtQ_dVm = np.zeros((Nsam, branch.shape[0], Nbus))
#     dtP_dVa = np.zeros((Nsam, branch.shape[0], Nbus-1))
#     dtQ_dVa = np.zeros((Nsam, branch.shape[0], Nbus-1))
#     dtS_dVm = np.dot(diagtV, Yt.dot(diagVnorm).conj()) + np.dot(diagtI.conj(), np.dot(tinc,diagVnorm))
#     dtS_dVa = -1j*np.dot(diagtV, Yt.dot(diagV).conj()) + 1j*np.dot(diagtI.conj(), np.dot(tinc, diagV))
#     dtP_dVm = np.real(dtS_dVm)
#     dtQ_dVm = np.imag(dtS_dVm)
#     dtP_dVa = np.real(dtS_dVa[:, bus_Va])
#     dtQ_dVa = np.imag(dtS_dVa[:, bus_Va])

    return dPfbus_dV, dQfbus_dV

In [20]:
# neural setting
input_channels = xtrain.shape[1]
output_channels_vm = yvmtrain.shape[1]
output_channels_va = yvatrain.shape[1]
lossvm = [] # save training losses of Vm
lossva = [] # save training losses of Va

# determine size of hidden layers
if x.shape[1] >= 100:
    hidden_units = 128
elif x.shape[1] > 30:
    hidden_units = 64
else:
    hidden_units = 16

In [21]:
# train model if it is not test
if flag_test == 0:
    model_vm = NetVm(input_channels,output_channels_vm,hidden_units,khidden_Vm)
    optimizer_vm = torch.optim.Adam(model_vm.parameters(), lr=Lrm)

    if torch.cuda.is_available():
        model_vm.to(device)
        print('model_vm.to(device)')

    MAXMIN_V = MAXMIN_V.to(device)
    print('*' * 5+'Vm training'+'*' * 5)
    #Training process: Voltage magnitude
    start_time = time.process_time()
    for epoch in range(EpochVm):
        running_loss = 0.0
        for step, (train_x, train_y) in enumerate(training_loader_vm):
            #feedforward
            train_x, train_y= train_x.to(device), train_y.to(device)
            yvmtrain_hat = model_vm(train_x)    

            # if epoch less than specified number/no penalty of V: only MSEloss
            loss = criterion(train_y, yvmtrain_hat)
            running_loss =  running_loss + loss.item()
            
            # backproprogate
            optimizer_vm.zero_grad()
            loss.backward()
            optimizer_vm.step()      

        lossvm.append(running_loss)

        if (epoch+1)%p_epoch == 0:          
            print('epoch', epoch+1, running_loss,torch.min(yvmtrain_hat).detach(),torch.max(yvmtrain_hat).detach())
         
        # save trianed model
        if (epoch+1)%100 == 0 and (epoch+1) >= s_epoch:            
            torch.save(model_vm.state_dict(), PATHVms+'E'+str(epoch+1)+'F'+str(flagVm)+'.pth',_use_new_zipfile_serialization=False)
            
    time_trianVm = time.process_time()-start_time  
    print("\n")        
    print('time_trianVm',round(time_trianVm,5),'seconds')
    print("\n")
    
    # save trianed model
    torch.save(model_vm.state_dict(), PATHVm,_use_new_zipfile_serialization=False)
    # plot training loss 
    fig = plt.figure()
    plt.plot(lossvm)
    plt.title('lossvm')

In [22]:
# testing Vm using training data
if flag_test == 0:
    print('test training data')
    xtrain = xtrain.to(device) 
    yvmtrain_hat = model_vm(xtrain)
    yvmtrain_hat = yvmtrain_hat.cpu()
    yvmtrains = yvmtrain/scale_vm*(VmUb - VmLb) + VmLb
    yvmtrain_hats = yvmtrain_hat.detach()/scale_vm*(VmUb - VmLb) + VmLb
    yvmtrain_hat_clip = get_clamp(yvmtrain_hats, hisVm_min, hisVm_max)

    mae_Vmtrain = get_mae(yvmtrains, yvmtrain_hat_clip.detach())
    mre_Vmtrain = get_rerr(yvmtrains,yvmtrain_hats.detach())
    mre_Vmtrain_clip = get_rerr(yvmtrains,yvmtrain_hat_clip.detach())

In [23]:
if flag_test == 0:
    #Training process: voltage angle
    model_va = NetVa(input_channels,output_channels_va,hidden_units,khidden_Vm)
    optimizer_va = torch.optim.Adam(model_va.parameters(), lr=Lra)
    model_va.to(device)
    print('model_va.to(device)')
    
    start_time = time.process_time()
    for epoch in range(EpochVa):
        running_loss = 0.0
        for step, (train_x, train_y) in enumerate(training_loader_va):
            #feedforward
            train_x, train_y = train_x.to(device), train_y.to(device)
            yvatrain_hat = model_va(train_x)
            loss = criterion(train_y, yvatrain_hat)
            running_loss =  running_loss + loss.item()

            # backproprogate
            optimizer_va.zero_grad()
            loss.backward()
            optimizer_va.step()

        lossva.append(running_loss)

        if (epoch+1)%p_epoch == 0:          
            print('epoch', epoch+1, running_loss, torch.min(yvatrain_hat).detach(),torch.max(yvatrain_hat).detach())

        # save trianed model
        if (epoch+1)%100 == 0 and (epoch+1)>= s_epoch:           
            torch.save(model_va.state_dict(), PATHVas +'E'+str(epoch+1)+'F'+str(flagVa)+'.pth',_use_new_zipfile_serialization=False)

    time_trianVa = time.process_time() - start_time  
    
    print("\n")        
    print('time_trianVa',round(time_trianVa,5), 'seconds')
    print("\n")  
    
    # save trianed model
    torch.save(model_va.state_dict(), PATHVa, _use_new_zipfile_serialization=False)
    fig = plt.figure()
    plt.plot(lossva)
    plt.title('lossva')

In [24]:
# testing Va using training data
if flag_test == 0:
    print('test trianing data')
    xtrain = xtrain.to(device)
    yvatrain_hat = model_va(xtrain)
    yvatrain_hat = yvatrain_hat.cpu()
    yvatrains = yvatrain/scale_va
    yvatrain_hats = yvatrain_hat.detach()/scale_va

    mae_Vatrain = get_mae(yvatrains, yvatrain_hats)
    mre_Vatrain = get_rerr(yvatrains,yvatrain_hats)

In [25]:
## save mat data
scale_vm = np.double(scale_vm)
scale_va = np.double(scale_va)

xtest = xtest.to(device)  

# Real_Vatrain = np.insert(Real_Vatrain.numpy(), bus_slack, values = 0, axis=1)
# Real_Vtrain = Real_Vmtrain.numpy()* np.exp(1j *Real_Vatrain)
# Real_Ptrain, Real_Qtrain = get_PQ(Real_Vtrain)
# Real_PQtrain = np.concatenate((Real_Ptrain, Real_Qtrain), axis = 1)
# Real_PQtrain = torch.from_numpy(Real_PQtrain)

# # train load generation for generation constraints
# Real_Pdtrain = RPd[0: Ntrain]/baseMVA
# Real_Qdtrain = RQd[0: Ntrain]/baseMVA
# Real_PQdtrain = np.concatenate((Real_Pdtrain, Real_Qdtrain), axis = 1)

# incidance matricx of branch from
finc = np.zeros((branch.shape[0], Nbus), dtype = float)
tinc = np.zeros((branch.shape[0], Nbus), dtype = float)
for i in range(branch.shape[0]):
    finc[i,  branch[i, 0]-1] = 1
    tinc[i,  branch[i, 1]-1] = 1
# real Vm Va for testing samples
yvmtests = yvmtest/scale_vm*(VmUb - VmLb) + VmLb
yvatests = yvatest/scale_va
    
# Va
Real_Va = yvatests.clone().numpy() * scale_va  # TEST: ADD VA SCALING HERE
Real_Va = np.insert(Real_Va, bus_slack, values = 0, axis=1)

# V
Real_V = yvmtests.numpy() * np.exp(1j *Real_Va)
# Pg QG
Real_Pg, Real_Qg, Real_Pd, Real_Qd = get_genload(Real_V, Pdtest, Qdtest, bus_Pg, bus_Qg) 

# Jocobian matrix for Pg Qg violation
dPbus_dV,dQbus_dV = dPQbus_dV(his_V,bus_Pg,bus_Qg)

# Jocobian matrix for branch flow violation
bus_Va = np.delete(np.arange(Nbus),bus_slack)
dPfbus_dV, dQfbus_dV = dSlbus_dV(his_V,bus_Va)

# load trained model if it is testing
if flag_test == 1:
    # load trained model 
    print('load trained model: model_vm_load')
    model_vm = NetVm(input_channels,output_channels_vm,hidden_units,khidden_Vm)
    model_vm.load_state_dict(torch.load(PATHVm, map_location=device))
    model_vm.eval()
    model_vm.to(device)       
    # load trained model 
    print('load trained model: model_va_load')
    model_va = NetVa(input_channels,output_channels_va,hidden_units,khidden_Vm)
    model_va.load_state_dict(torch.load(PATHVa, map_location=device))
    model_va.eval() 
    model_va.to(device)   

load trained model: model_vm_load
load trained model: model_va_load


In [26]:
print('*'*5+'begin repeated calcualtion for time testing'+'*'*5)  
Pred_timeVm_NN_log = np.zeros(REPEAT)
Pred_timeVa_NN_log = np.zeros(REPEAT)
Pred_PQgtime_log = np.zeros((REPEAT,2))
Pred_timeVm_log = np.zeros((REPEAT,2))
Pred_timeVa_log = np.zeros((REPEAT,2))
full_time = np.zeros((REPEAT,2))
sample_time = np.zeros(Nsample_test)

for k in range(REPEAT):
    if (k+1)%10 == 0:
        print('REPEAT',k+1)
            
    # Predicted data
    start_time_all = time.process_time()
    
    time_PredVm_NN = 0
    yvmtest_hat = torch.zeros((Ntest, Nbus))
    for step, (test_x, test_y) in enumerate(test_loader_vm):
        test_x = test_x.to(device) 
        start_time = time.process_time()
        yvmtest_hat[step] = model_vm(test_x)
        delta_time = time.process_time() - start_time
        time_PredVm_NN = time_PredVm_NN + delta_time
        sample_time[step] += delta_time
    
    yvmtest_hat = yvmtest_hat.cpu()
    start_time = time.process_time()
    yvmtest_hats = yvmtest_hat.detach()/scale_vm*(VmUb - VmLb) + VmLb
    yvmtest_hat_clip = get_clamp(yvmtest_hats, hisVm_min, hisVm_max)
    time_PredVm = time.process_time() - start_time
    sample_time += time_PredVm/Ntest
    time_PredVm = time_PredVm + time_PredVm_NN
    

    time_PredVa_NN = 0
    yvatest_hat = torch.zeros((Ntest, Nbus-1))
    for step, (test_x, test_y) in enumerate(test_loader_va):
        test_x = test_x.to(device)
        start_time = time.process_time()
        yvatest_hat[step] = model_va(test_x)
        delta_time = time.process_time() - start_time
        time_PredVa_NN = time_PredVa_NN + delta_time
        sample_time[step] += delta_time

    yvatest_hat = yvatest_hat.cpu()
    start_time = time.process_time()
    yvatest_hats = yvatest_hat.detach()/scale_va
    time_PredVa = time.process_time() - start_time
    sample_time += time_PredVa/Ntest
    time_PredVa = time_PredVa + time_PredVa_NN
    
    # Va
    Pred_Va = yvatest_hats.clone().numpy()
    Pred_Va = np.insert(Pred_Va, bus_slack, values = 0, axis=1)
    
    ## calculate Pg QG
    start_time = time.process_time()
    Pred_V = yvmtest_hat_clip.clone().numpy()* np.exp(1j * Pred_Va)  # predicted V
    Pred_Pg, Pred_Qg, Pred_Pd, Pred_Qd = get_genload(Pred_V, Pdtest, Qdtest, bus_Pg, bus_Qg)
    Pred_PQgtime = time.process_time() - start_time
    sample_time += Pred_PQgtime/Ntest
    time_no_post_processing = time.process_time() - start_time_all
    
    # Pg Qg violation
    lsPg,lsQg,lsidxPg,lsidxQg,vio_PQgmaxmin,vio_PQg,deltaPgL,deltaPgU,deltaQgL,deltaQgU,vio_PQgmaxminnum = get_vioPQg(Pred_Pg, bus_Pg, MAXMIN_Pg, Pred_Qg, bus_Qg, MAXMIN_Qg)
    lsidxPQg = np.squeeze(np.array(np.where((lsidxPg + lsidxQg) > 0)))
    num_viotest = np.size(lsidxPQg) # number of violated samples

    # revise power flow (from)
    vio_branang,vio_branpf,deltapf,vio_branpfidx,lsSf,_,lsSf_sampidx,_ = get_viobran2(Pred_V,Pred_Va,branch,Yf,Yt)
    vio_branpf_num = np.size(np.where(vio_branpfidx>0))
    lsSf_sampidx = np.asarray(lsSf_sampidx)

    # post-processing of Vm Va 
    Pred_Va1 = Pred_Va.copy()
    Pred_Vm1 = yvmtest_hat_clip.clone().numpy()

    start_time = time.process_time()
    if flag_hisv:
        print('\nUse historical V to calculate dV')
        dV1 = get_hisdV(lsPg,lsQg,lsidxPg,lsidxQg,num_viotest,k_dV,bus_Pg,bus_Qg,dPbus_dV,dQbus_dV)
    else:
        print('\nUse predicted V to calculate dV')
        dV1 = get_dV(Pred_V,lsPg,lsQg,lsidxPg,lsidxQg,num_viotest,k_dV,bus_Pg,bus_Qg)

    if vio_branpf_num > 0:
        dV_branch = np.zeros((lsSf_sampidx.shape[0], Nbus*2))
        start_time = time.process_time()
        for i in range(lsSf_sampidx.shape[0]):
            # Pl/deltaSl
            mp = np.array(lsSf[i][:, 2]/lsSf[i][:, 1]).reshape(-1, 1)
            mq = np.array(lsSf[i][:, 3]/lsSf[i][:, 1]).reshape(-1, 1)
            # dPf_dVaVm
            dPdV = dPfbus_dV[np.array(lsSf[i][:, 0].astype(int)).squeeze(), :] 
            # dQf_dVaVm
            dQdV = dQfbus_dV[np.array(lsSf[i][:, 0].astype(int)).squeeze(), :]
            dmp = mp*dPdV 
            dmq = mq*dQdV
            # M: dS_dVaVm
            dmpq_inv = np.linalg.pinv(dmp+dmq)
            dV_branch[i] = np.dot(dmpq_inv, np.array(lsSf[i][:, 1])).squeeze()
        dV1 = dV1 + dV_branch

    # dV
    Pred_Va1[lsidxPQg, :] = Pred_Va[lsidxPQg, :] - dV1[:, 0:Nbus]
    Pred_Va1[:,bus_slack] = 0
    Pred_Vm1[lsidxPQg, :] = yvmtest_hat_clip.numpy()[lsidxPQg, :] - dV1[:, Nbus:2*Nbus]
    Pred_Vm1_clip = get_clamp(torch.from_numpy(Pred_Vm1), hisVm_min, hisVm_max)
    Pred_V1 = Pred_Vm1_clip.numpy() * np.exp(1j*Pred_Va1) # revised V
    Pred_Pg1, Pred_Qg1, Pred_Pd1, Pred_Qd1 = get_genload(Pred_V1, Pdtest, Qdtest, bus_Pg, bus_Qg)
    Pred_PQgtime1 = time.process_time() - start_time
    
    sample_time += Pred_PQgtime1/Ntest
    
    time_all = time.process_time() - start_time_all
    full_time[k,0] = time_no_post_processing/Ntest
    full_time[k,1] = time_all/Ntest
    
    
    # save time
    Pred_timeVm_NN_log[k] = time_PredVm_NN/Ntest
    Pred_timeVa_NN_log[k] = time_PredVa_NN/Ntest
    Pred_PQgtime_log[k,0] = Pred_PQgtime/Ntest
    Pred_PQgtime_log[k,1] = Pred_PQgtime1/Ntest
    Pred_timeVm_log[k,0] = (Pred_PQgtime + time_PredVm)/Ntest
    Pred_timeVa_log[k,0] = (Pred_PQgtime + time_PredVa)/Ntest
    Pred_timeVm_log[k,1] = (Pred_PQgtime + Pred_PQgtime1 + time_PredVm)/Ntest
    Pred_timeVa_log[k,1] = (Pred_PQgtime + Pred_PQgtime1 + time_PredVa)/Ntest
    
    
print('*'*5+'end repeated calcualtion for time testing'+'*'*5) 

# performance evaluation
# no revison
mae_Vmtest = get_mae(yvmtests, yvmtest_hat_clip.detach())
mre_Vmtest_clip = get_rerr(yvmtests,yvmtest_hat_clip.detach())
mae_Vatest = get_mae(yvatests, yvatest_hats)
mre_Vatest = get_rerr(yvatests, yvatest_hats)
# after post-processing
mae_Vmtest1 = get_mae(yvmtests, Pred_Vm1_clip)
mae_Vatest1 = get_mae(torch.from_numpy(Real_Va).float(), torch.from_numpy(Pred_Va1).float())

# load satisfaction
mre_Pd = get_rerr2(torch.from_numpy(Real_Pd.sum(axis=1)), torch.from_numpy(Pred_Pd.sum(axis=1)))
mre_Qd = get_rerr2(torch.from_numpy(Real_Qd.sum(axis=1)), torch.from_numpy(Pred_Qd.sum(axis=1)))
mre_Pd1 = get_rerr2(torch.from_numpy(Real_Pd.sum(axis=1)), torch.from_numpy(Pred_Pd1.sum(axis=1)))
mre_Qd1 = get_rerr2(torch.from_numpy(Real_Qd.sum(axis=1)), torch.from_numpy(Pred_Qd1.sum(axis=1)))

# optimality loss
# no revison
Pred_cost = get_Pgcost(Pred_Pg,idxPg,gencost)
Real_cost = get_Pgcost(Real_Pg,idxPg,gencost)
mre_cost = get_rerr2(torch.from_numpy(Real_cost), torch.from_numpy(Pred_cost))
# after post-processing
Pred_cost1 = get_Pgcost(Pred_Pg1,idxPg,gencost)
mre_cost1 = get_rerr2(torch.from_numpy(Real_cost), torch.from_numpy(Pred_cost1))

# branch violation
vio_branang,vio_branpf,deltapf,vio_branangnum,vio_branpfnum = get_viobran(Pred_V,Pred_Va,branch,Yf,Yt)
if deltapf.shape[1] > 2:
    res_branpf = np.array((np.mean(deltapf[:,1]),np.max(deltapf[:,1]),np.mean(deltapf[:,2]),np.max(deltapf[:,2])))
else:
    res_branpf = np.array((np.mean(deltapf[:,1]),np.max(deltapf[:,1])))

# Pg Qg violation degree
res_PQUL = np.zeros((2, 8))
res_PQUL[0] = np.array((np.mean(deltaPgL[:,1]),np.min(deltaPgL[:,1]),np.mean(deltaPgU[:,1]),np.max(deltaPgU[:,1]), \
                          np.mean(deltaQgL[:,1]),np.min(deltaQgL[:,1]),np.mean(deltaQgU[:,1]),np.max(deltaQgU[:,1])))

# Pg Qg violation after post-processing
_,_,lsidxPg1,lsidxQg1,vio_PQgmaxmin1,vio_PQg1,deltaPgL1,deltaPgU1,deltaQgL1,deltaQgU1,vio_PQgmaxminnum1 = get_vioPQg(Pred_Pg1, bus_Pg, MAXMIN_Pg, Pred_Qg1, bus_Qg, MAXMIN_Qg)
lsidxPQg1 = np.squeeze(np.array(np.where(lsidxPg1 + lsidxQg1> 0)))
num_viotest1 = np.size(lsidxPQg)
# Pg Qg violation degree after revision
res_PQUL[1] = np.array((np.mean(deltaPgL1[:,1]),np.min(deltaPgL1[:,1]),np.mean(deltaPgU1[:,1]),np.max(deltaPgU1[:,1]), \
                          np.mean(deltaQgL1[:,1]),np.min(deltaQgL1[:,1]),np.mean(deltaQgU1[:,1]),np.max(deltaQgU1[:,1])))

# branch violation after post-processing
vio_branang1,vio_branpf1,deltapf1,vio_branangnum1,vio_branpfnum1 = get_viobran(Pred_V1,Pred_Va1,branch,Yf,Yt)
if deltapf1.shape[1] > 2:
    res_branpf1 = np.array((np.mean(deltapf1[:,1]),np.max(deltapf1[:,1]),np.mean(deltapf1[:,2]),np.max(deltapf1[:,2])))
else:
    res_branpf1 = np.array((np.mean(deltapf1[:,1]),np.max(deltapf1[:,1])))

# save results
resvio = torch.zeros(2, 7)
resvio1 = torch.zeros(2, 7)
resvio[0] = torch.tensor([torch.mean(mre_cost),torch.mean(mre_Pd),torch.mean(mre_Qd), torch.mean(vio_PQg[:, 0]), torch.mean(vio_PQg[:, 1]), \
                         torch.mean(vio_branang), torch.mean(vio_branpf)]) 
resvio[1] = torch.tensor([torch.mean(mre_cost1),torch.mean(mre_Pd1),torch.mean(mre_Qd1), torch.mean(vio_PQg1[:, 0]), torch.mean(vio_PQg1[:, 1]), \
                         torch.mean(vio_branang1), torch.mean(vio_branpf1)]) 
resvio1[0] = torch.tensor([torch.max(mre_cost),torch.max(mre_Pd),torch.max(mre_Qd), torch.min(vio_PQg[:, 0]), torch.min(vio_PQg[:, 1]), \
                         torch.min(vio_branang), torch.min(vio_branpf)])
resvio1[1] = torch.tensor([torch.max(mre_cost1),torch.max(mre_Pd1),torch.max(mre_Qd1), torch.min(vio_PQg1[:, 0]), torch.min(vio_PQg1[:, 1]), \
                         torch.min(vio_branang1), torch.min(vio_branpf1)]) 

resvio = np.around(resvio.numpy(), decimals=2)
resvio1 = np.around(resvio1.numpy(), decimals=2)
maeV = np.double(torch.tensor([[mae_Vmtest, mae_Vatest],[mae_Vmtest1, mae_Vatest1]]).numpy())
lossvm = np.array(lossvm)
lossva = np.array(lossva)
PredtimeVm = np.mean(Pred_timeVm_log, axis=0)
PredtimeVa = np.mean(Pred_timeVa_log, axis=0)
mre_cost = np.array(mre_cost)
mre_cost1 = np.array(mre_cost1)
scipy.io.savemat(resultnm, \
mdict={'resvio': resvio,'resvio1': resvio1,'maeV': maeV,'res_PQUL': res_PQUL,'deltaPgL': deltaPgL,'deltaPgU': deltaPgU,'deltaQgL': deltaQgL,'deltaQgU': deltaQgU, \
    'PredtimeVm': PredtimeVm,'PredtimeVa': PredtimeVa,'Pred_timeVm_log': Pred_timeVm_log,'Pred_timeVa_log': Pred_timeVa_log, \
    'deltaPgL1': deltaPgL1,'deltaPgU1': deltaPgU1,'deltaQgL1': deltaQgL1,'deltaQgU1': deltaQgU1,'deltapf':deltapf,'deltapf1':deltapf1, \
    'res_branpf':res_branpf,'res_branpf1':res_branpf1,'mre_cost':mre_cost,'mre_cost1':mre_cost1,'Pred_timeVm_NN_log':Pred_timeVm_NN_log, \
    'Pred_timeVa_NN_log':Pred_timeVa_NN_log,'Pred_PQgtime_log':Pred_PQgtime_log
})

*****begin repeated calcualtion for time testing*****

Use historical V to calculate dV
*****end repeated calcualtion for time testing*****


In [27]:
mre_cost1[100]

-9.204921502748991

In [28]:
vio_PQgmaxmin[100, :]

tensor([84.2105, 94.7368, 94.4444, 94.4444])

In [29]:
Real_cost[100], Pred_cost[100], Pred_cost1[100]

(32023.145863811504, 32227.72657038119, 29075.440424336844)

In [30]:
Pred_Pg[100, :], Real_Pg[100, :]

(array([ 0.05531876,  0.43732497,  0.09294419,  0.08342136,  0.34073725,
         0.45509369,  1.2724763 ,  1.25755824,  2.96525346,  0.13631975,
        -0.02918052,  0.83157469,  0.52357032,  1.57617544,  0.00996541,
         0.35757681,  0.65964972,  0.47253714,  0.03304314]),
 array([ 0.06043296,  0.41063759,  0.10112442,  0.08750232,  0.32884098,
         0.46051921,  1.39930571,  1.24648462,  2.99404756,  0.18347765,
        -0.0901222 ,  0.82482125,  0.48869225,  1.61212023,  0.00977713,
         0.35611645,  0.67709413,  0.4687181 ,  0.0331017 ]))

In [31]:
np.min(Real_Pg)

-0.1019674312545587

In [32]:
Pgt = RPg[0: Ntrain, idxPg]/baseMVA
np.max(Pgt)

0.1097665003

In [33]:
np.max(RPd[:,:])

3.478929279

In [34]:
MAXMIN_Pg

array([[ 5.05,  0.  ],
       [ 0.85,  0.  ],
       [ 2.21,  0.  ],
       [ 4.85,  0.  ],
       [ 0.17,  0.  ],
       [ 0.2 ,  0.  ],
       [ 2.23,  0.  ],
       [ 0.53,  0.  ],
       [ 3.08,  0.  ],
       [ 1.95,  0.  ],
       [ 4.41,  0.  ],
       [ 7.84,  0.  ],
       [11.82,  0.  ],
       [ 5.09,  0.  ],
       [ 0.1 ,  0.  ],
       [ 6.37,  0.  ],
       [ 6.53,  0.  ],
       [ 1.08,  0.  ],
       [ 0.79,  0.  ]])

In [35]:
print('***************Summary result case',Nbus, 'sys_R', sys_R,'***************')
print('training setting: Ntrain',Ntrain,' Ntest',Ntest, 'batch_size',batch_size_training,\
      'Lm', Lm,'La', La,' Lrm', Lrm,' Lra', Lra,' EpochVm',EpochVm,'scale_va',scale_va,'  scale_vm',scale_vm)
print('NN layer: hidden_units',hidden_units,' khidden_Vm',khidden_Vm*hidden_units ,'khidden_Va',khidden_Va*hidden_units )
print(model_vm)
print(model_va)
print('\n','*'*20,'before modification: ','*'*20)
print('mae_Vmtest', mae_Vmtest,'mae_Vatest', mae_Vatest)
print('num_viotest', num_viotest)
print('vio_Pgmax: mean', torch.mean(vio_PQgmaxmin[:,0]).numpy(), '%  max', torch.max(vio_PQgmaxmin[:,0]).numpy(), \
      'vio_Pgmin: mean',torch.mean(vio_PQgmaxmin[:,1]).numpy(), '%  max', torch.max(vio_PQgmaxmin[:,1]).numpy())
print('vio_Qgmax: mean', torch.mean(vio_PQgmaxmin[:,2]).numpy(), '%  max', torch.max(vio_PQgmaxmin[:,2]), \
      'vio_Qgmin: mean',torch.mean(vio_PQgmaxmin[:,3]).numpy(), '%  max', torch.max(vio_PQgmaxmin[:,3]).numpy())
print('vio_Pgmaxmin: mean', torch.mean(vio_PQg[:, 0]).numpy(), '%  max', torch.max(vio_PQg[:, 0]).numpy(), \
      'vio_Qgmaxmin: mean',torch.mean(vio_PQg[:, 1]).numpy(), '%  max', torch.max(vio_PQg[:, 1]).numpy())
print('mean', torch.mean(vio_branang).numpy(), '%  max', torch.max(vio_branang).numpy(),'% ', \
      'vio_branpf: mean',torch.mean(vio_branpf).numpy(), '%  max', torch.max(vio_branpf).numpy(),'% ')
print('mean mre_cost', resvio[0,0],'%  ','mre_Pd',resvio[0,1],'%  ','mre_Qd',resvio[0,2],'vio_PQg',resvio[0,3],'%  ', \
      'vio_PQg',resvio[0,4],'%  ','vio_branang',resvio[0,5],'%  ', 'vio_branpf',resvio[0,6],'%  ')

print('\n','*'*20,'after post-processing: ','*'*20)
print('mae_Vmtest1', mae_Vmtest1,'mae_Vatest1', mae_Vatest1)
print('num_viotest1', num_viotest1) 
print('vio_Pgmax: mean', torch.mean(vio_PQgmaxmin1[:,0]).numpy(), '%  max', torch.max(vio_PQgmaxmin1[:,0]).numpy(), \
      'vio_Pgmin: mean',torch.mean(vio_PQgmaxmin1[:,1]).numpy(), '%  max', torch.max(vio_PQgmaxmin1[:,1]).numpy())
print('vio_Qgmax: mean', torch.mean(vio_PQgmaxmin1[:,2]).numpy(), '%  max', torch.max(vio_PQgmaxmin1[:,2]).numpy(), \
      'vio_Qgmin: mean',torch.mean(vio_PQgmaxmin1[:,3]).numpy(), '%  max', torch.max(vio_PQgmaxmin1[:,3]).numpy())
print('vio_Pgmaxmin: mean', torch.mean(vio_PQg1[:, 0]).numpy(), '%  max', torch.max(vio_PQg1[:, 0]).numpy(), \
      'vio_Qgmaxmin: mean',torch.mean(vio_PQg1[:, 1]).numpy(), '%  max', torch.max(vio_PQg1[:, 1]).numpy())
print('vio_branang: mean', torch.mean(vio_branang1).numpy(), '%  max', torch.max(vio_branang1).numpy(),'% ', \
      'vio_branpf: mean',torch.mean(vio_branpf1).numpy(), '%  max', torch.max(vio_branpf1).numpy(),'% ')
print('mean mre_cost', resvio[1,0],'%  ','mre_Pd',resvio[1,1],'%  ','mre_Qd',resvio[1,2],'%  ', \
      'vio_PQg',resvio[1,3],'%  ','vio_PQg',resvio[1,4],'%  ','vio_branang',resvio1[1,5],'%  ', 'vio_branpf',resvio[1,6],'%  ')

if flag_test == 0:
    print('\n', '*'*10,'trian vs test','*'*10)
    print('voltage')
    print('mae_Vmtrain', mae_Vmtrain)
    print('mre_Vmtrain_clip', torch.mean(mre_Vmtrain_clip),'%  ',  torch.max(mre_Vmtrain_clip),'%')
    print('mae_Vmtest', mae_Vmtest)
    print('mre_Vmtest_clip', torch.mean(mre_Vmtest_clip),'%  ',  torch.max(mre_Vmtest_clip),'%')
    print('angle')
    print('mae_Vatrain', mae_Vatrain)
    print('mre_Vatrain', torch.min(mre_Vatrain),'%', torch.mean(mre_Vatrain),'%  ',  torch.max(mre_Vatrain),'%')
    print('mae_Vatest', mae_Vatest)
    print('mre_Vatest', torch.mean(mre_Vatest),'%  ',  torch.max(mre_Vatest),'%')
    print('time_trianVm',round(time_trianVm,6),'sec  time_trianVa',round(time_trianVa,6), \
          'sec  \ntime_trianVm',round(time_trianVm/60,6),'min  time_trianVa',round(time_trianVa/60,6),'min  \n')
    
print('\n','*'*20,'computation time','*'*20)
print('Pred_time for each sample:\nPred_timeVm',np.round(PredtimeVm[0],7),'sec\nPred_timeVa',np.round(PredtimeVa[0],7),'sec')
print('PredtimeVa',PredtimeVa,'PredtimeVm',PredtimeVm)

***************Summary result case 118 sys_R 1 ***************
training setting: Ntrain 80000  Ntest 20000 batch_size 100 Lm 3 La 3  Lrm 0.001  Lra 0.001  EpochVm 100 scale_va 10.0   scale_vm 10.0
NN layer: hidden_units 128  khidden_Vm [1024  512  256] khidden_Va [1024  512  256]
NetVm(
  (fc1): Linear(in_features=198, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (fcbfend): Linear(in_features=256, out_features=118, bias=True)
  (fcend): Linear(in_features=118, out_features=118, bias=True)
)
NetVa(
  (fc1): Linear(in_features=198, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=512, bias=True)
  (fc3): Linear(in_features=512, out_features=256, bias=True)
  (fcbfend): Linear(in_features=256, out_features=117, bias=True)
  (fcend): Linear(in_features=117, out_features=117, bias=True)
)

 ******************** before modification:  ********************

In [36]:
# Saving pre-processing results
Pred_Pd
Pred_Qd
Pred_Pg
Pred_Qg

array([[ 0.12468286,  0.73300193,  0.4603447 , ..., -0.08367309,
         0.41840433,  2.0028826 ],
       [ 0.05742539,  0.60349659,  0.30432961, ...,  0.01941929,
         0.32647484,  2.08404347],
       [ 0.02550797,  1.20298556,  0.30858733, ...,  0.35685975,
         0.09266847,  3.56939106],
       ...,
       [ 0.10607186,  1.2772077 ,  0.43299647, ..., -0.08012976,
         1.00788016,  2.28148696],
       [ 0.00462355,  0.33235761,  0.38597293, ...,  0.12263716,
         0.20777377,  2.44561994],
       [-0.02379801,  1.33950644,  0.45358402, ...,  0.32444351,
         0.39080526,  3.03644169]])

In [37]:
# Saving post-processing results
Pred_Pd1 
Pred_Qd1
Pred_Pg1
Pred_Qg1
Pred_Vm1
Pred_Va1

array([[-0.0084529 , -0.00855853, -0.00818521, ..., -0.00209765,
        -0.00894074, -0.00260435],
       [-0.00813586, -0.00812137, -0.00790309, ..., -0.00210012,
        -0.00841752, -0.00384649],
       [-0.01145982, -0.01102658, -0.01105524, ..., -0.00239887,
        -0.0110996 , -0.0032854 ],
       ...,
       [-0.01104938, -0.01092719, -0.01073864, ..., -0.00216009,
        -0.01144346, -0.00306071],
       [-0.00882436, -0.00867866, -0.00846258, ..., -0.00251908,
        -0.00901818, -0.00311782],
       [-0.00961637, -0.0094385 , -0.00921378, ..., -0.00270274,
        -0.00977763, -0.0034752 ]], dtype=float32)

In [38]:
full_time

array([[0.00294687, 0.00440469]])

In [39]:
np.min(sample_time)

0.0010796875000000001

In [40]:
Pred_Va1 - Real_Va*10

array([[0.07774517, 0.07851219, 0.07508763, ..., 0.0212469 , 0.07966153,
        0.03412386],
       [0.07550827, 0.07455824, 0.0734302 , ..., 0.01890756, 0.07423241,
        0.03635065],
       [0.10268311, 0.09954742, 0.09938974, ..., 0.02209581, 0.10005306,
        0.03400012],
       ...,
       [0.10077998, 0.09902065, 0.09790316, ..., 0.01986235, 0.10493749,
        0.02762113],
       [0.08067691, 0.07973283, 0.07701912, ..., 0.02289818, 0.0837148 ,
        0.02718997],
       [0.08627795, 0.08521253, 0.08284418, ..., 0.02492962, 0.08872727,
        0.03248107]], dtype=float32)

In [41]:
Real_Vatrain

tensor([[-0.0086, -0.0087, -0.0083,  ..., -0.0023, -0.0089, -0.0037],
        [-0.0084, -0.0083, -0.0081,  ..., -0.0021, -0.0083, -0.0040],
        [-0.0114, -0.0111, -0.0110,  ..., -0.0024, -0.0111, -0.0037],
        ...,
        [-0.0092, -0.0089, -0.0087,  ..., -0.0016, -0.0089, -0.0031],
        [-0.0097, -0.0094, -0.0093,  ..., -0.0026, -0.0095, -0.0034],
        [-0.0096, -0.0093, -0.0093,  ..., -0.0024, -0.0096, -0.0028]])

In [42]:
Real_Va*10

array([[-0.08619808, -0.08707072, -0.08327284, ..., -0.02334455,
        -0.08860227, -0.03672821],
       [-0.08364414, -0.08267961, -0.08133329, ..., -0.02100768,
        -0.08264993, -0.04019714],
       [-0.11414294, -0.11057399, -0.11044498, ..., -0.02449469,
        -0.11115266, -0.03728552],
       ...,
       [-0.11182936, -0.10994784, -0.1086418 , ..., -0.02202244,
        -0.11638096, -0.03068184],
       [-0.08950128, -0.08841149, -0.0854817 , ..., -0.02541726,
        -0.09273298, -0.03030779],
       [-0.09589433, -0.09465103, -0.09205796, ..., -0.02763237,
        -0.09850491, -0.03595627]], dtype=float32)

In [43]:
diff_Pd = (Pred_Pd[:,load_idx] - Real_Pd[:,load_idx]) / Real_Pd[:, load_idx]
sample_diff = np.sqrt(np.mean((diff_Pd)**2,axis=1))
sample_diff

array([ 0.99977455,  1.09193598, 13.48595862, ...,  0.44234484,
        1.56887437,  1.80297181])

In [44]:
np.min(sample_diff)

0.25683107344417455

In [45]:
diff_Pd

array([[-0.69168497,  2.3935652 ,  0.63550492, ..., -0.0785442 ,
         0.19750053,  0.09893257],
       [-0.22897731, -0.0093739 , -0.04451412, ...,  0.46207705,
         0.08390618,  0.09928983],
       [-0.24493341,  0.10038149,  0.23602672, ..., -0.20019014,
         0.03668962,  0.02078687],
       ...,
       [-0.20667142,  0.2194422 ,  0.34886898, ..., -0.25202629,
         0.1398325 , -0.09155935],
       [-0.43340976, -0.07366764,  0.14580698, ..., -0.24235174,
        -0.30449336,  0.10416568],
       [ 0.11753844, -0.14319215, -0.01339483, ..., -0.10246597,
        -0.03087641,  0.01517777]])

In [58]:
# Check sample mean, max, min runtimes
a = sample_time
#np.savetxt("DeepOPF-V_timing.csv", a, delimiter=",")
np.mean(a), np.max(a), np.min(a)

(0.003209375, 0.1260796875, 0.0010796875000000001)

In [47]:
# Save predicted costs
#np.savetxt("DeepOPF-V_PredCost.csv", Pred_cost, delimiter=",")

In [48]:
# Cast violation number tensors to numpy arrays
vio_branangnum, vio_branpfnum, vio_PQgmaxminnum = np.array(vio_branangnum), np.array(vio_branpfnum), np.array(vio_PQgmaxminnum)
vio_PQgnum = np.sum(vio_PQgmaxminnum, axis=1)

vio_num = vio_branangnum + vio_branpfnum + vio_PQgnum
vio_num

array([13., 14.,  9., ..., 11., 11., 10.], dtype=float32)

In [49]:
vio_branangnum1, vio_branpfnum1, vio_PQgmaxminnum1 = np.array(vio_branangnum1), np.array(vio_branpfnum1), np.array(vio_PQgmaxminnum1)
vio_PQgnum1 = np.sum(vio_PQgmaxminnum1, axis=1)

vio_num1 = vio_branangnum1 + vio_branpfnum1 + vio_PQgnum1
vio_num1

array([10.,  7.,  4., ..., 11.,  3.,  3.], dtype=float32)

In [51]:
perc_infeasible_gen = vio_PQgnum1 / len(gen)
avg_infeasible_gen = np.mean(perc_infeasible_gen)
avg_infeasible_gen

0.10198982

In [53]:
# Check mean/max/min number of violated gen constraints
np.mean(vio_PQgnum1), np.max(vio_PQgnum1), np.min(vio_PQgnum1)

(5.50745, 15.0, 0.0)

In [54]:
# Check mean/max/min number of violated gen constraints, no post-processing
np.mean(vio_PQgnum), np.max(vio_PQgnum), np.min(vio_PQgnum)

(10.4293, 21.0, 3.0)

In [ ]:
# Check if there are any branch angle of pf violations
sum(vio_branangnum + vio_branpfnum)

In [ ]:
# Check cost optimality for violation of Pd < x%
idx_Pd_gt_sample = (np.sum(Pred_Pd1[:,load_idx],axis=1) - np.sum(Real_Pd[:,load_idx],axis=1)) / np.sum(Real_Pd[:, load_idx],axis=1) < 10
diff_cost = (Pred_cost1[idx_Pd_gt_sample] - Real_cost[idx_Pd_gt_sample]) / Real_cost[idx_Pd_gt_sample]
sample_diff = np.min((diff_cost))
sample_diff

In [52]:
sum(idx_Pd_gt_sample)

NameError: name 'idx_Pd_gt_sample' is not defined

In [ ]:
# Check cost optimality for violation of Qd < x%
idx_Qd_gt_sample = (np.sum(Pred_Pd1[:,load_idx],axis=1) - np.sum(Real_Pd[:,load_idx],axis=1)) / np.sum(Real_Pd[:, load_idx],axis=1) < 10
diff_cost = (Pred_cost1[idx_Qd_gt_sample] - Real_cost[idx_Qd_gt_sample]) / Real_cost[idx_Qd_gt_sample]
sample_diff = np.min((diff_cost))
sample_diff

In [ ]:
# Check violation of Pd > 1%
np.sum(np.abs((np.sum(Pred_Pd1[:,load_idx],axis=1) - np.sum(Real_Pd[:,load_idx],axis=1)) / np.sum(Real_Pd[:, load_idx],axis=1)) > 0.01)

In [ ]:
# Check violation of Qd > 1%
np.sum(np.abs((np.sum(Pred_Qd[:,load_idx],axis=1) - np.sum(Real_Qd[:,load_idx],axis=1)) / np.sum(Real_Qd[:, load_idx],axis=1)) > 0.01)